### ISSUE TITLE
Server resource pack

### ISSUE THREAD

**Issue by SaviorD22** [JamCoreModding/quicker-connect-button#1]
Everytime I use quicker connect button to access a server I get prompted to download a resource pack, but when using the multiplayer button, there's an option to just accept it.  Can a "Server resource pack" option be added to the config?

**Comment by Jamalam360** [comment]
Sure, I'll look into it at some point.

p.s. saw your discord DM as well, but replying here for transparency with others who might be wondering about this issue

**Comment by Jamalam360** [comment]
I'll release an update late tonight with the `resourcePackBehaviour` config option, which can be set to `ENABLED` to disable any prompts

**Comment by SaviorD22** [comment]
Don't only apply it to 1.20.4, I need it for 1.20.1 :)
