### ISSUE TITLE
port not change

### ISSUE THREAD

**Issue by raykoshima** [JamCoreModding/quicker-connect-button#2]
I change port to my server's port but it still use 25565
![image (12)](https://github.com/JamCoreModding/quicker-connect-button/assets/64307199/815cf1ce-20c2-4ecf-bda5-13820b1397bc)
in the config file (ip is change but port not)
![image](https://github.com/JamCoreModding/quicker-connect-button/assets/64307199/b6549071-a8e7-45dc-aa73-fed0015cfd6d)

**Comment by Jamalam360** [comment]
Thanks for reporting, but I cannot reproduce this on the latest version and unfortunately earlier versions are out of support :(
