### ISSUE TITLE
Support for 1.20.1

### ISSUE THREAD

**Issue by SaviorD22** [JamCoreModding/quicker-connect-button#3]
The new version of quicker connect button (2.1.0) adds resourcepack behavoir option but only to the 1.20.4 version.  Could it be possible to apply this new feature to 1.20.1? many modded servers are in that version and it would be cool to join them with 1 click from the main menu.

**Comment by Jamalam360** [comment]
may be done at some point but 1.20.5/6 updates are my current priority

**Comment by Jamalam360** [comment]
I decided against doing this, sorry
