### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by KIRUYXAN** [JamCoreModding/quicker-connect-button#6]
Why is the mod not updated on versions 1.20 and 1.20.1?

**Comment by Jamalam360** [comment]
https://docs.jamalam.tech/supported-versions/

**Comment by KIRUYXAN** [comment]
In the end I still don't understand why

**Comment by Jamalam360** [comment]
The versions just aren't supported any more. I can't support too many versions at once as I just spend my whole time backporting updates then
